### PR TITLE
Do not use cache in ComponentLoader

### PR DESCRIPTION
**Pull request by aretecode**
so it will work work with noflo 0.7.*

### CODE REVIEW

**Comment by trustmaster** [comment]
... but will leak memory at large in NoFlo 0.5.x. I think component cache should be resolved at NoFlo level rather than patching it here.

**Comment by aretecode** [comment]
If you version bump it and require noflo 0.7.x then all old projects wont be affected. Resolving at NoFlo level does seem better, could just disable the cache in NoFlo 7 for now since it doesn't work.

**Comment by trustmaster** [comment]
I mean that this problem can affect other packages too.

**Comment by bergie** [comment]
What's the exact issue with component cache here?

**Comment by trustmaster** [comment]
@bergie If i recall it correctly, there is a conflict between `.noflo.json` and `fbp-manifest`

**Comment by bergie** [comment]
@trustmaster as in, conflict between old-format file and new loader?

**Comment by trustmaster** [comment]
@bergie here's a quote by @aretecode (from a project using `noflo-paypal` as dependency):

> So the `fbp.json` has `paypal` instead of `noflo-paypal`. And the `noflo-tester` has `cache: true` which triggered error `filter is undefined` in ComponentLoader.

**Comment by aretecode** [comment]
Files didn't matter. A clean `package.json`, no `.noflo.json`, and with a preheated `fbp.json`. The problem is using `cache: true`. https://github.com/noflo/noflo/issues/427

**Pull request closed without merging**
